//! Rust types for iDoris's wire contracts.
//!
//! The **real source of truth** stays `packages/contracts/schema/*.schema.json`
//! (JSON Schema, draft 2020-12) — this crate is a hand-written Rust
//! projection of those files, the same role `packages/contracts/src/generated/*`
//! (zod, generated by `pnpm gen:contracts`) plays on the TS side. Two gates
//! keep this crate honest instead of a codegen step:
//!
//! - `tests/contract_drift.rs` re-reads every schema file and asserts its
//!   `properties`/`required` sets match the [`shape::SchemaShape`] constants
//!   declared next to each struct (the Rust equivalent of
//!   `pnpm check:contract-drift`).
//! - `tests/parity.rs` runs a shared corpus of valid/invalid sample JSON
//!   (ported from `packages/contracts/tests/contract/parity.test.ts`)
//!   through both this crate's [`error::parse`] and the `jsonschema` crate
//!   validating directly against the schema file, and asserts they agree.
//!
//! Every object type derives `#[serde(deny_unknown_fields)]`, matching the
//! TS side's zod `.strict()` behaviour — unknown fields are a hard error on
//! both sides.

pub mod adapter_manifest;
pub mod admin_v0;
pub mod common;
pub mod component_card;
pub mod deploy_mode;
pub mod error;
pub mod load_policy;
pub mod provider;
pub mod routing_policy;
pub mod shape;
pub mod task_profile;
pub mod tenant;
pub mod training_sample;
pub mod version;

pub use adapter_manifest::AdapterManifest;
pub use component_card::ComponentCard;
pub use deploy_mode::DeployMode;
pub use error::{Contract, ContractError, parse};
pub use load_policy::LoadPolicy;
pub use provider::ProviderDescriptor;
pub use routing_policy::RoutingPolicy;
pub use shape::SchemaShape;
pub use task_profile::TaskProfile;
pub use tenant::TenantContext;
pub use training_sample::TrainingSample;
pub use version::CONTRACT_VERSION;
