//! Read-only Admin API v0 facts plus its authenticated router/listener contract.
//! The Admin router is separate from the data plane and callers must bind it
//! through [`AdminBindConfig`], which is fixed to IPv4 loopback.

use std::sync::Arc;

use axum::{
    Json, Router,
    extract::{Request, State},
    http::{
        HeaderMap, StatusCode,
        header::{self, AUTHORIZATION},
    },
    middleware::{self, Next},
    response::{Html, IntoResponse, Response},
    routing::get,
};
use serde::Serialize;
use subtle::ConstantTimeEq;
use uuid::Uuid;

use crate::AppState;
use idoris_contracts::admin_v0::{
    AdminAdmissionStatus, AdminBackend, AdminBackendsResponse, AdminCapacityEntry,
    AdminCapacitySnapshot, AdminCapacityState, AdminStatusResponse,
};
use idoris_policy::ROLES;

pub const ADMIN_PORT_ENV: &str = "IDORIS_ADMIN_PORT";
pub const DEFAULT_ADMIN_PORT: u16 = 8741;
pub const ADMIN_BIND_HOST: std::net::Ipv4Addr = std::net::Ipv4Addr::LOCALHOST;

const SESSION_TOKEN_LEN: usize = 64;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AdminPortError(String);

impl std::fmt::Display for AdminPortError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

impl std::error::Error for AdminPortError {}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AdminBindConfig {
    port: u16,
}

impl AdminBindConfig {
    /// Parse the dedicated Admin listener port. Unset/blank uses the public
    /// Admin default; explicit values must be plain decimal TCP ports.
    pub fn parse(raw: Option<&str>) -> Result<Self, AdminPortError> {
        let raw = match raw.map(str::trim) {
            None | Some("") => {
                return Ok(Self {
                    port: DEFAULT_ADMIN_PORT,
                });
            }
            Some(raw) => raw,
        };
        if !raw.bytes().all(|byte| byte.is_ascii_digit()) {
            return Err(AdminPortError(format!(
                "{ADMIN_PORT_ENV} 不是合法的端口号：'{raw}'。请设置为 1-65535 之间的整数"
            )));
        }
        let port: u64 = raw.parse().map_err(|_| {
            AdminPortError(format!(
                "{ADMIN_PORT_ENV} 不是合法的端口号：'{raw}'。请设置为 1-65535 之间的整数"
            ))
        })?;
        if !(1..=u16::MAX as u64).contains(&port) {
            return Err(AdminPortError(format!(
                "{ADMIN_PORT_ENV} 不是合法的端口号：'{raw}'。请设置为 1-65535 之间的整数"
            )));
        }
        Ok(Self { port: port as u16 })
    }

    pub fn port(self) -> u16 {
        self.port
    }

    pub fn addr(self) -> std::net::SocketAddr {
        std::net::SocketAddr::from((ADMIN_BIND_HOST, self.port))
    }

    pub async fn bind(self) -> std::io::Result<tokio::net::TcpListener> {
        tokio::net::TcpListener::bind(self.addr()).await
    }
}

pub struct AdminSessionToken(String);

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AdminTokenError;

impl std::fmt::Display for AdminTokenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("Admin session token 必须是 64 位小写十六进制字符串")
    }
}

impl std::error::Error for AdminTokenError {}

impl AdminSessionToken {
    pub fn mint() -> Self {
        Self(format!(
            "{}{}",
            Uuid::new_v4().simple(),
            Uuid::new_v4().simple()
        ))
    }

    /// Explicit one-time exposure for delivering the token to the local
    /// management client. Never log or persist this value.
    pub fn expose_secret(&self) -> &str {
        &self.0
    }

    /// Accept a token generated by a trusted local launcher. The launcher must
    /// generate all 64 hex digits from a cryptographically secure random
    /// source. It may retain the same secret in process memory for Admin
    /// requests; callers must not put it in argv, environment variables, logs,
    /// or files.
    pub fn from_launcher_secret(secret: &[u8]) -> Result<Self, AdminTokenError> {
        if secret.len() != SESSION_TOKEN_LEN
            || !secret
                .iter()
                .all(|byte| byte.is_ascii_digit() || matches!(byte, b'a'..=b'f'))
        {
            return Err(AdminTokenError);
        }
        let secret = std::str::from_utf8(secret).map_err(|_| AdminTokenError)?;
        Ok(Self(secret.to_owned()))
    }

    pub fn matches(&self, candidate: &str) -> bool {
        if candidate.len() != SESSION_TOKEN_LEN {
            return false;
        }
        bool::from(self.0.as_bytes().ct_eq(candidate.as_bytes()))
    }
}

impl std::fmt::Debug for AdminSessionToken {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("AdminSessionToken([REDACTED])")
    }
}

impl std::fmt::Display for AdminSessionToken {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("[REDACTED]")
    }
}

#[derive(Clone)]
struct AdminHttpState {
    app: Arc<AppState>,
    token: Arc<AdminSessionToken>,
}

/// Build the Admin listener router. Its static console shell carries no privileged
/// data; every `/admin/api/v1/*` resource remains bearer-authenticated. The caller
/// owns the separate loopback listener; this router is never mounted on [`crate::build_app`].
pub fn build_admin_app(state: AppState, token: AdminSessionToken) -> Router {
    let state = AdminHttpState {
        app: Arc::new(state),
        token: Arc::new(token),
    };
    let api = Router::new()
        .route("/status", get(admin_status))
        .route("/backends", get(admin_backends))
        .route("/models", get(admin_models))
        .route("/roles", get(admin_roles))
        .route("/runtimes", get(admin_runtimes))
        .fallback(StatusCode::NOT_FOUND)
        .layer(middleware::from_fn_with_state(
            state.clone(),
            require_admin_auth,
        ))
        .with_state(state);

    Router::new()
        .route("/admin/", get(admin_console))
        .nest("/admin/api/v1", api)
        .fallback(StatusCode::NOT_FOUND)
}

const ADMIN_CONSOLE_HTML: &str = r#"<!doctype html>
<html lang="en">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>iDoris Admin</title>
<style>
body{font-family:system-ui,sans-serif;max-width:960px;margin:2rem auto;padding:0 1rem;background:#111;color:#eee}
label,button{font:inherit} input{font:inherit;width:32rem;max-width:100%} button{margin-left:.5rem}
pre{white-space:pre-wrap;overflow-wrap:anywhere;border:1px solid #444;padding:1rem;border-radius:.4rem}
.error{color:#ff9b9b}
</style>
<h1>iDoris Admin</h1>
<p>Paste the launcher-provided Admin session token. It is used only in page memory for these read-only requests.</p>
<label>Session token <input id="token" type="password" autocomplete="off" spellcheck="false"></label>
<button id="refresh" type="button">Refresh</button>
<p id="message" class="error" role="status"></p>
<div id="results"></div>
<script>
(() => {
  const resources = ['status','backends','models','roles','runtimes'];
  const input = document.getElementById('token');
  const results = document.getElementById('results');
  const message = document.getElementById('message');
  document.getElementById('refresh').addEventListener('click', async () => {
    const token = input.value;
    input.value = '';
    results.replaceChildren();
    message.textContent = '';
    if (!token) { message.textContent = 'Session token is required.'; return; }
    for (const resource of resources) {
      const section = document.createElement('section');
      const title = document.createElement('h2');
      const output = document.createElement('pre');
      title.textContent = resource;
      output.textContent = 'Loading…';
      section.append(title, output);
      results.append(section);
      try {
        const response = await fetch(`/admin/api/v1/${resource}`, {
          method: 'GET',
          headers: {Authorization: `Bearer ${token}`},
          cache: 'no-store',
          credentials: 'omit'
        });
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        output.textContent = JSON.stringify(await response.json(), null, 2);
      } catch (error) {
        output.textContent = error instanceof Error ? error.message : 'Request failed';
      }
    }
  });
})();
</script>
</html>"#;

async fn admin_console() -> impl IntoResponse {
    (
        [
            (header::CACHE_CONTROL, "no-store"),
            (header::REFERRER_POLICY, "no-referrer"),
            (header::X_CONTENT_TYPE_OPTIONS, "nosniff"),
            (
                header::CONTENT_SECURITY_POLICY,
                "default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'",
            ),
        ],
        Html(ADMIN_CONSOLE_HTML),
    )
}

async fn require_admin_auth(
    State(state): State<AdminHttpState>,
    request: Request,
    next: Next,
) -> Response {
    if !authorized(request.headers(), &state.token) {
        return StatusCode::UNAUTHORIZED.into_response();
    }
    next.run(request).await
}

fn authorized(headers: &HeaderMap, token: &AdminSessionToken) -> bool {
    let mut values = headers.get_all(AUTHORIZATION).iter();
    let Some(value) = values.next() else {
        return false;
    };
    if values.next().is_some() {
        return false;
    }
    let Ok(value) = value.to_str() else {
        return false;
    };
    let Some((scheme, candidate)) = value.split_once(' ') else {
        return false;
    };
    if scheme.is_empty()
        || candidate.is_empty()
        || scheme.bytes().any(|byte| byte.is_ascii_whitespace())
        || candidate.chars().any(char::is_whitespace)
        || candidate.contains(',')
    {
        return false;
    }
    scheme.eq_ignore_ascii_case("bearer") && token.matches(candidate)
}

async fn admin_status(State(state): State<AdminHttpState>) -> Json<AdminStatusResponse> {
    let status = status(&state.app);
    Json(AdminStatusResponse {
        status: status.status.to_string(),
        service: status.service.to_string(),
        version: status.version,
        contract_version: status.contract_version.to_string(),
        instance_id: status.instance_id,
        components: status.components,
        runtimes: status.runtimes,
        subscriptions: status.subscriptions,
        budget_configured: status.budget_configured,
        audit_configured: status.audit_configured,
        capacity: capacity(&state.app).await,
    })
}

async fn admin_backends(State(state): State<AdminHttpState>) -> Json<AdminBackendsResponse> {
    Json(AdminBackendsResponse(backends(&state.app)))
}

async fn admin_models(State(state): State<AdminHttpState>) -> Json<AdminModelsSnapshot> {
    Json(models(&state.app).await)
}

async fn admin_roles() -> Json<Vec<AdminRole>> {
    Json(roles())
}

async fn admin_runtimes(State(state): State<AdminHttpState>) -> Json<AdminRuntimesSnapshot> {
    Json(runtimes(&state.app).await)
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct AdminStatus {
    pub status: &'static str,
    pub service: &'static str,
    pub version: String,
    pub contract_version: &'static str,
    pub instance_id: String,
    pub components: usize,
    pub runtimes: usize,
    pub subscriptions: usize,
    pub budget_configured: bool,
    pub audit_configured: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum AdminModelSourceKind {
    HttpModelsEndpoint,
    SubscriptionRegistration,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum AdminModelSourceState {
    Observed,
    Configured,
    Error,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum AdminModelSourceError {
    Unavailable,
    AuthenticationFailed,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct AdminModelSource {
    pub provider_id: String,
    pub source: AdminModelSourceKind,
    pub state: AdminModelSourceState,
    pub models: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<AdminModelSourceError>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct AdminModelsSnapshot {
    pub sources: Vec<AdminModelSource>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum AdminRuntimeState {
    Observed,
    Error,
}

#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct AdminRuntime {
    pub provider_id: String,
    pub state: AdminRuntimeState,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pressure: Option<idoris_backend::Pressure>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub used_gb: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model_memory_max_gb: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub loaded: Option<Vec<String>>,
}

#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct AdminRuntimesSnapshot {
    pub runtimes: Vec<AdminRuntime>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct AdminRole {
    pub role: &'static str,
    pub aliases: Vec<String>,
    pub catalog_role: bool,
}

pub fn status(state: &AppState) -> AdminStatus {
    AdminStatus {
        status: "ok",
        service: "idoris",
        version: env!("CARGO_PKG_VERSION").to_string(),
        contract_version: idoris_contracts::CONTRACT_VERSION,
        instance_id: state.instance_id.clone(),
        components: state.cards.len(),
        runtimes: state.runtimes.len(),
        subscriptions: state.subscriptions.len(),
        budget_configured: state.budget_ledger.is_some(),
        audit_configured: state.record_store.is_some(),
    }
}

/// Snapshot startup-validated backend configuration and local lifecycle
/// bindings only. This deliberately does not probe runtime health, models,
/// memory pressure, or network reachability.
pub fn backends(state: &AppState) -> Vec<AdminBackend> {
    state
        .cards
        .iter()
        .map(|card| AdminBackend {
            provider_id: card.provider.id.clone(),
            locality: card.provider.locality,
            form: card.form,
            lifecycle_runtime_bound: state.runtimes.get(&card.provider.id).is_some(),
        })
        .collect()
}

/// Snapshot the stable public role contract only. The aliases are accepted
/// model=idoris/<role> request names; they do not claim any configured or
/// currently available model serves the role.
pub fn roles() -> Vec<AdminRole> {
    ROLES
        .iter()
        .copied()
        .map(|role| AdminRole {
            role: role.as_str(),
            aliases: vec![format!("idoris/{}", role.as_str())],
            catalog_role: role.is_catalog_role(),
        })
        .collect()
}

/// Observe each active model source without collapsing failures into an
/// apparently complete flat list. HTTP model ids are runtime observations;
/// subscription ids are registration facts, not backend health claims.
pub async fn models(state: &AppState) -> AdminModelsSnapshot {
    let mut sources = Vec::new();
    for card in &state.cards {
        if card.form != idoris_contracts::component_card::Form::HttpService {
            continue;
        }
        let (state_kind, models, error) =
            match crate::models::observe_http_models(&state.http_client, card).await {
                Ok(crate::models::HttpModelObservation::Observed(entries)) => (
                    AdminModelSourceState::Observed,
                    entries.into_iter().map(|entry| entry.id).collect(),
                    None,
                ),
                Ok(crate::models::HttpModelObservation::Unavailable) => (
                    AdminModelSourceState::Error,
                    Vec::new(),
                    Some(AdminModelSourceError::Unavailable),
                ),
                Err(crate::models::ModelsError::UpstreamAuthenticationFailed { .. }) => (
                    AdminModelSourceState::Error,
                    Vec::new(),
                    Some(AdminModelSourceError::AuthenticationFailed),
                ),
            };
        sources.push(AdminModelSource {
            provider_id: card.provider.id.clone(),
            source: AdminModelSourceKind::HttpModelsEndpoint,
            state: state_kind,
            models,
            error,
        });
    }
    sources.extend(
        state
            .subscriptions
            .discovery()
            .into_iter()
            .map(|entry| AdminModelSource {
                provider_id: entry.provider_id,
                source: AdminModelSourceKind::SubscriptionRegistration,
                state: AdminModelSourceState::Configured,
                models: vec![entry.model_id],
                error: None,
            }),
    );
    AdminModelsSnapshot { sources }
}

/// Observe only lifecycle-managed runtimes. Resident direct HTTP cards are
/// intentionally absent because they do not have a `RuntimeRegistry` entry.
/// Backend failures are represented by `state=error`; free-form backend error
/// strings never become part of this management snapshot.
pub async fn runtimes(state: &AppState) -> AdminRuntimesSnapshot {
    let runtimes = state
        .runtimes
        .status_observations()
        .await
        .into_iter()
        .map(|(provider_id, status)| map_runtime_status(provider_id, status))
        .collect();
    AdminRuntimesSnapshot { runtimes }
}

fn map_runtime_status(
    provider_id: String,
    status: Result<idoris_backend::BackendStatus, idoris_backend::BackendError>,
) -> AdminRuntime {
    match status {
        Ok(status) => AdminRuntime {
            provider_id,
            state: AdminRuntimeState::Observed,
            pressure: Some(status.pressure),
            used_gb: Some(status.used_gb),
            model_memory_max_gb: Some(status.model_memory_max_gb),
            loaded: Some(status.loaded),
        },
        Err(_) => AdminRuntime {
            provider_id,
            state: AdminRuntimeState::Error,
            pressure: None,
            used_gb: None,
            model_memory_max_gb: None,
            loaded: None,
        },
    }
}

/// Snapshot the already-installed capacity provider without inventing a
/// fallback. Successful empty capacity is distinct from an unavailable
/// provider, and provider errors never expose free-form backend detail.
pub async fn capacity(state: &AppState) -> AdminCapacitySnapshot {
    let Some(provider) = &state.capabilities else {
        return AdminCapacitySnapshot {
            state: AdminCapacityState::Unavailable,
            entries: None,
        };
    };
    match provider.snapshot().await {
        Ok(entries)
            if entries.iter().any(|entry| {
                !entry.estimated_memory_gb.is_finite() || entry.estimated_memory_gb < 0.0
            }) =>
        {
            AdminCapacitySnapshot {
                state: AdminCapacityState::Error,
                entries: None,
            }
        }
        Ok(entries) => AdminCapacitySnapshot {
            state: AdminCapacityState::Observed,
            entries: Some(
                entries
                    .into_iter()
                    .map(|entry| AdminCapacityEntry {
                        id: entry.id,
                        capability: entry.capability,
                        resident: entry.resident,
                        estimated_memory_gb: entry.estimated_memory_gb,
                        ctx_limit: entry.ctx_limit,
                        queue_depth: entry.queue_depth,
                        admission_status: match entry.admission_status {
                            crate::capabilities::AdmissionStatus::Ready => {
                                AdminAdmissionStatus::Ready
                            }
                            crate::capabilities::AdmissionStatus::RequiresEviction => {
                                AdminAdmissionStatus::RequiresEviction
                            }
                            crate::capabilities::AdmissionStatus::Blocked => {
                                AdminAdmissionStatus::Blocked
                            }
                        },
                    })
                    .collect(),
            ),
        },
        Err(_) => AdminCapacitySnapshot {
            state: AdminCapacityState::Error,
            entries: None,
        },
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used)]

    use axum::body::Body;
    use axum::http::{HeaderValue, Request, StatusCode};
    use http_body_util::BodyExt;
    use tower::ServiceExt;
    use wiremock::{
        Mock, MockServer, ResponseTemplate,
        matchers::{method, path},
    };

    use super::*;

    #[test]
    fn launcher_token_requires_exact_canonical_shape() {
        let valid = b"0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef";
        let token = AdminSessionToken::from_launcher_secret(valid).unwrap();
        assert!(token.matches(std::str::from_utf8(valid).unwrap()));
        for invalid in [
            &valid[..63],
            b"0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdeF".as_slice(),
            b"0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdeg".as_slice(),
        ] {
            assert!(AdminSessionToken::from_launcher_secret(invalid).is_err());
        }
    }

    #[derive(Clone)]
    struct FakeCapabilities {
        entries: Option<Vec<crate::capabilities::CapabilityEntry>>,
    }

    #[derive(Clone)]
    struct CountingCapabilities {
        calls: std::sync::Arc<std::sync::atomic::AtomicUsize>,
    }

    impl crate::capabilities::CapabilitiesProvider for FakeCapabilities {
        fn snapshot(
            &self,
        ) -> std::pin::Pin<
            Box<
                dyn std::future::Future<
                        Output = Result<
                            Vec<crate::capabilities::CapabilityEntry>,
                            crate::capabilities::CapabilitiesError,
                        >,
                    > + Send
                    + '_,
            >,
        > {
            Box::pin(async move {
                self.entries.clone().ok_or_else(|| {
                    crate::capabilities::CapabilitiesError::new(
                        "secret backend detail must never escape Admin snapshot",
                    )
                })
            })
        }
    }

    impl crate::capabilities::CapabilitiesProvider for CountingCapabilities {
        fn snapshot(
            &self,
        ) -> std::pin::Pin<
            Box<
                dyn std::future::Future<
                        Output = Result<
                            Vec<crate::capabilities::CapabilityEntry>,
                            crate::capabilities::CapabilitiesError,
                        >,
                    > + Send
                    + '_,
            >,
        > {
            self.calls.fetch_add(1, std::sync::atomic::Ordering::SeqCst);
            Box::pin(async { Ok(Vec::new()) })
        }
    }

    #[test]
    fn admin_port_defaults_and_validates_override() {
        for raw in [None, Some(""), Some("   ")] {
            assert_eq!(
                AdminBindConfig::parse(raw).unwrap().port(),
                DEFAULT_ADMIN_PORT
            );
        }
        for raw in [Some("0"), Some("65536"), Some("-1"), Some("+9"), Some("8x")] {
            assert!(AdminBindConfig::parse(raw).is_err(), "{raw:?}");
        }
        assert_eq!(AdminBindConfig::parse(Some(" 1 ")).unwrap().port(), 1);
        assert_eq!(AdminBindConfig::parse(Some("9000")).unwrap().port(), 9000);
        assert_eq!(AdminBindConfig::parse(Some("65535")).unwrap().port(), 65535);
    }

    #[tokio::test]
    async fn admin_bind_is_ipv4_loopback_only_and_conflicts_fail_closed() {
        let reservation = std::net::TcpListener::bind((ADMIN_BIND_HOST, 0)).unwrap();
        let port = reservation.local_addr().unwrap().port();
        drop(reservation);
        let config = AdminBindConfig::parse(Some(&port.to_string())).unwrap();

        assert_eq!(config.addr().ip(), std::net::IpAddr::V4(ADMIN_BIND_HOST));
        let listener = config.bind().await.unwrap();
        assert_eq!(listener.local_addr().unwrap(), config.addr());
        assert!(
            config.bind().await.is_err(),
            "an occupied Admin port must be rejected, never replaced"
        );
    }

    #[tokio::test]
    async fn capacity_snapshot_preserves_observed_entries_and_successful_empty() {
        use std::sync::Arc;

        let entry = crate::capabilities::CapabilityEntry {
            id: "model-a".into(),
            capability: "reasoning".into(),
            resident: true,
            estimated_memory_gb: 12.5,
            ctx_limit: 131_072,
            queue_depth: 3,
            admission_status: crate::capabilities::AdmissionStatus::RequiresEviction,
        };
        for entries in [vec![entry.clone()], Vec::new()] {
            let expected = entries
                .iter()
                .map(|entry| AdminCapacityEntry {
                    id: entry.id.clone(),
                    capability: entry.capability.clone(),
                    resident: entry.resident,
                    estimated_memory_gb: entry.estimated_memory_gb,
                    ctx_limit: entry.ctx_limit,
                    queue_depth: entry.queue_depth,
                    admission_status: AdminAdmissionStatus::RequiresEviction,
                })
                .collect();
            let state = AppState {
                capabilities: Some(Arc::new(FakeCapabilities {
                    entries: Some(entries.clone()),
                })),
                ..AppState::default()
            };
            assert_eq!(
                capacity(&state).await,
                AdminCapacitySnapshot {
                    state: AdminCapacityState::Observed,
                    entries: Some(expected),
                }
            );
        }
    }

    #[tokio::test]
    async fn capacity_snapshot_distinguishes_unavailable_from_sanitized_error() {
        use std::sync::Arc;

        assert_eq!(
            capacity(&AppState::default()).await,
            AdminCapacitySnapshot {
                state: AdminCapacityState::Unavailable,
                entries: None,
            }
        );

        let state = AppState {
            capabilities: Some(Arc::new(FakeCapabilities { entries: None })),
            ..AppState::default()
        };
        let snapshot = capacity(&state).await;
        assert_eq!(snapshot.state, AdminCapacityState::Error);
        assert_eq!(snapshot.entries, None);
        let json = serde_json::to_string(&snapshot).unwrap();
        assert_eq!(json, r#"{"state":"error"}"#);
        assert!(!json.contains("secret backend detail"));
    }

    #[tokio::test]
    async fn capacity_snapshot_rejects_invalid_memory_facts() {
        use std::sync::Arc;

        for estimated_memory_gb in [-1.0, f64::NAN, f64::INFINITY, f64::NEG_INFINITY] {
            let state = AppState {
                capabilities: Some(Arc::new(FakeCapabilities {
                    entries: Some(vec![crate::capabilities::CapabilityEntry {
                        id: "model-a".into(),
                        capability: "reasoning".into(),
                        resident: true,
                        estimated_memory_gb,
                        ctx_limit: 131_072,
                        queue_depth: 0,
                        admission_status: crate::capabilities::AdmissionStatus::Ready,
                    }]),
                })),
                ..AppState::default()
            };
            assert_eq!(
                capacity(&state).await,
                AdminCapacitySnapshot {
                    state: AdminCapacityState::Error,
                    entries: None,
                }
            );
        }
    }

    #[tokio::test]
    async fn data_plane_router_does_not_expose_admin_paths() {
        for path in [
            "/admin/api/v1/status",
            "/admin/api/v1/backends",
            "/admin/api/v1/models",
            "/admin/api/v1/roles",
            "/admin/api/v1/runtimes",
            "/admin/api/v1/capacity",
            "/admin/",
        ] {
            let response = crate::build_app(AppState::default())
                .oneshot(Request::builder().uri(path).body(Body::empty()).unwrap())
                .await
                .unwrap();
            assert_eq!(response.status(), StatusCode::NOT_FOUND);
        }
    }

    #[tokio::test]
    async fn admin_console_is_static_local_shell_with_hardened_headers() {
        let token = AdminSessionToken::mint();
        let secret = token.expose_secret().to_string();
        let app = build_admin_app(AppState::default(), token);
        let response = app
            .oneshot(
                Request::builder()
                    .uri("/admin/")
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(response.status(), StatusCode::OK);
        let headers = response.headers();
        assert_eq!(headers.get(header::CACHE_CONTROL).unwrap(), "no-store");
        assert_eq!(headers.get(header::REFERRER_POLICY).unwrap(), "no-referrer");
        assert_eq!(
            headers.get(header::X_CONTENT_TYPE_OPTIONS).unwrap(),
            "nosniff"
        );
        let csp = headers
            .get(header::CONTENT_SECURITY_POLICY)
            .unwrap()
            .to_str()
            .unwrap();
        assert!(csp.contains("connect-src 'self'"));
        assert!(csp.contains("frame-ancestors 'none'"));

        let body = response.into_body().collect().await.unwrap().to_bytes();
        let html = String::from_utf8(body.to_vec()).unwrap();
        assert!(!html.contains(&secret));
        for forbidden in [
            "localStorage",
            "sessionStorage",
            "indexedDB",
            "document.cookie",
            "location.search",
            "location.hash",
            "<script src=",
            "http://",
            "https://",
        ] {
            assert!(
                !html.contains(forbidden),
                "forbidden console source: {forbidden}"
            );
        }
        for resource in ["status", "backends", "models", "roles", "runtimes"] {
            assert!(
                html.contains(resource),
                "missing console resource: {resource}"
            );
        }
        assert!(html.contains("type=\"password\""));
        assert!(html.contains("Authorization: `Bearer ${token}`"));
    }

    fn admin_request(path: &str, scheme: &str, secret: &str) -> Request<Body> {
        Request::builder()
            .uri(path)
            .header(AUTHORIZATION, format!("{scheme} {secret}"))
            .body(Body::empty())
            .unwrap()
    }

    #[tokio::test]
    async fn admin_auth_failures_are_identical_and_bearer_scheme_is_case_insensitive() {
        let token = AdminSessionToken::mint();
        let secret = token.expose_secret().to_string();
        let wrong = AdminSessionToken::mint().expose_secret().to_string();
        let app = build_admin_app(AppState::default(), token);

        for scheme in ["Bearer", "bearer", "BEARER"] {
            let response = app
                .clone()
                .oneshot(admin_request("/admin/api/v1/status", scheme, &secret))
                .await
                .unwrap();
            assert_eq!(response.status(), StatusCode::OK, "{scheme}");
        }

        let mut duplicate = admin_request("/admin/api/v1/status", "Bearer", &secret);
        duplicate.headers_mut().append(
            AUTHORIZATION,
            HeaderValue::from_str(&format!("Bearer {secret}")).unwrap(),
        );
        let mut invalid_utf8 = Request::builder()
            .uri("/admin/api/v1/status")
            .body(Body::empty())
            .unwrap();
        invalid_utf8
            .headers_mut()
            .insert(AUTHORIZATION, HeaderValue::from_bytes(&[0xff]).unwrap());
        let requests = [
            Request::builder()
                .uri("/admin/api/v1/status")
                .body(Body::empty())
                .unwrap(),
            admin_request("/admin/api/v1/status", "Basic", &secret),
            Request::builder()
                .uri("/admin/api/v1/status")
                .header(AUTHORIZATION, "Bearer")
                .body(Body::empty())
                .unwrap(),
            Request::builder()
                .uri("/admin/api/v1/status")
                .header(AUTHORIZATION, format!("Bearer {secret} extra"))
                .body(Body::empty())
                .unwrap(),
            Request::builder()
                .uri("/admin/api/v1/status")
                .header(AUTHORIZATION, format!("Bearer\t{secret}"))
                .body(Body::empty())
                .unwrap(),
            Request::builder()
                .uri("/admin/api/v1/status")
                .header(AUTHORIZATION, format!("Bearer {secret},Bearer {secret}"))
                .body(Body::empty())
                .unwrap(),
            admin_request("/admin/api/v1/status", "Bearer", &wrong),
            duplicate,
            invalid_utf8,
            Request::builder()
                .method("POST")
                .uri("/admin/api/v1/status")
                .body(Body::empty())
                .unwrap(),
            Request::builder()
                .uri("/admin/api/v1/unknown")
                .body(Body::empty())
                .unwrap(),
        ];
        let mut bodies = Vec::new();
        for request in requests {
            let response = app.clone().oneshot(request).await.unwrap();
            assert_eq!(response.status(), StatusCode::UNAUTHORIZED);
            bodies.push(response.into_body().collect().await.unwrap().to_bytes());
        }
        assert!(bodies.iter().all(|body| body == &bodies[0]));
        assert!(!String::from_utf8_lossy(&bodies[0]).contains(&secret));
    }

    #[tokio::test]
    async fn unauthorized_status_never_calls_capacity_provider() {
        use std::sync::{Arc, atomic::AtomicUsize};

        let calls = Arc::new(AtomicUsize::new(0));
        let token = AdminSessionToken::mint();
        let app = build_admin_app(
            AppState {
                capabilities: Some(Arc::new(CountingCapabilities {
                    calls: calls.clone(),
                })),
                ..AppState::default()
            },
            token,
        );
        let response = app
            .oneshot(
                Request::builder()
                    .uri("/admin/api/v1/status")
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(response.status(), StatusCode::UNAUTHORIZED);
        assert_eq!(calls.load(std::sync::atomic::Ordering::SeqCst), 0);
    }

    #[tokio::test]
    async fn authenticated_admin_router_exposes_only_the_five_read_routes() {
        let token = AdminSessionToken::mint();
        let secret = token.expose_secret().to_string();
        let app = build_admin_app(AppState::default(), token);

        for path in [
            "/admin/api/v1/status",
            "/admin/api/v1/backends",
            "/admin/api/v1/models",
            "/admin/api/v1/roles",
            "/admin/api/v1/runtimes",
        ] {
            let response = app
                .clone()
                .oneshot(admin_request(path, "Bearer", &secret))
                .await
                .unwrap();
            assert_eq!(response.status(), StatusCode::OK, "{path}");
        }
        for path in ["/admin/api/v1/capacity", "/admin/api/v1/unknown"] {
            let response = app
                .clone()
                .oneshot(admin_request(path, "Bearer", &secret))
                .await
                .unwrap();
            assert_eq!(response.status(), StatusCode::NOT_FOUND, "{path}");
        }
        let response = app
            .oneshot(
                Request::builder()
                    .method("POST")
                    .uri("/admin/api/v1/status")
                    .header(AUTHORIZATION, format!("Bearer {secret}"))
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(response.status(), StatusCode::METHOD_NOT_ALLOWED);
    }

    #[tokio::test]
    async fn admin_status_embeds_capacity_and_sanitizes_provider_errors() {
        use std::sync::Arc;

        let entry = crate::capabilities::CapabilityEntry {
            id: "model-a".into(),
            capability: "reasoning".into(),
            resident: true,
            estimated_memory_gb: 12.5,
            ctx_limit: 131_072,
            queue_depth: 3,
            admission_status: crate::capabilities::AdmissionStatus::Ready,
        };
        for entries in [Some(vec![entry]), None] {
            let token = AdminSessionToken::mint();
            let secret = token.expose_secret().to_string();
            let app = build_admin_app(
                AppState {
                    capabilities: Some(Arc::new(FakeCapabilities { entries })),
                    ..AppState::default()
                },
                token,
            );
            let response = app
                .oneshot(admin_request("/admin/api/v1/status", "Bearer", &secret))
                .await
                .unwrap();
            assert_eq!(response.status(), StatusCode::OK);
            let body = response.into_body().collect().await.unwrap().to_bytes();
            let json: serde_json::Value = serde_json::from_slice(&body).unwrap();
            assert!(json.get("capacity").is_some());
            assert!(!String::from_utf8_lossy(&body).contains("secret backend detail"));
        }
    }

    #[tokio::test]
    async fn admin_status_wire_shape_matches_the_shared_v0_contract() {
        let state = AppState::default();
        let instance_id = state.instance_id.clone();
        let token = AdminSessionToken::mint();
        let secret = token.expose_secret().to_string();
        let response = build_admin_app(state, token)
            .oneshot(admin_request("/admin/api/v1/status", "Bearer", &secret))
            .await
            .unwrap();
        assert_eq!(response.status(), StatusCode::OK);
        let body = response.into_body().collect().await.unwrap().to_bytes();
        let value: serde_json::Value = serde_json::from_slice(&body).unwrap();
        assert_eq!(
            value,
            serde_json::json!({
                "status": "ok",
                "service": "idoris",
                "version": env!("CARGO_PKG_VERSION"),
                "contract_version": idoris_contracts::CONTRACT_VERSION,
                "instance_id": instance_id,
                "components": 0,
                "runtimes": 0,
                "subscriptions": 0,
                "budget_configured": false,
                "audit_configured": false,
                "capacity": {"state": "unavailable"},
            })
        );
        assert!(idoris_contracts::parse::<AdminStatusResponse>(&value).is_ok());
    }

    #[tokio::test]
    async fn admin_backends_wire_shape_matches_the_shared_v0_contract() {
        let token = AdminSessionToken::mint();
        let secret = token.expose_secret().to_string();
        let response = build_admin_app(AppState::default(), token)
            .oneshot(admin_request("/admin/api/v1/backends", "Bearer", &secret))
            .await
            .unwrap();
        assert_eq!(response.status(), StatusCode::OK);
        let body = response.into_body().collect().await.unwrap().to_bytes();
        let value: serde_json::Value = serde_json::from_slice(&body).unwrap();
        assert_eq!(value, serde_json::json!([]));
        assert!(idoris_contracts::parse::<AdminBackendsResponse>(&value).is_ok());
    }

    #[tokio::test]
    async fn admin_models_route_sanitizes_provider_failure() {
        let server = MockServer::start().await;
        Mock::given(method("GET"))
            .and(path("/v1/models"))
            .respond_with(ResponseTemplate::new(500).set_body_string("provider-secret"))
            .mount(&server)
            .await;
        let mut card: idoris_contracts::ComponentCard =
            serde_yaml::from_str(include_str!("../../../config/components/omlx.yaml")).unwrap();
        card.provider.id = "failed-provider".into();
        card.endpoint = server.uri();
        card.version_pin = "test@1".into();
        let token = AdminSessionToken::mint();
        let secret = token.expose_secret().to_string();
        let app = build_admin_app(
            AppState {
                cards: vec![card],
                ..AppState::default()
            },
            token,
        );
        let response = app
            .oneshot(admin_request("/admin/api/v1/models", "Bearer", &secret))
            .await
            .unwrap();
        assert_eq!(response.status(), StatusCode::OK);
        let body = response.into_body().collect().await.unwrap().to_bytes();
        assert!(!String::from_utf8_lossy(&body).contains("provider-secret"));
        assert_eq!(
            serde_json::from_slice::<serde_json::Value>(&body).unwrap()["sources"][0]["state"],
            "error"
        );
    }

    #[tokio::test]
    async fn backends_report_only_configured_facts_and_runtime_binding() {
        use std::sync::Arc;

        use idoris_backend::{MockAdapter, ModelInfo, Supervisor, SupervisorConfig};
        use idoris_contracts::Contract;
        use idoris_contracts::load_policy::{Admission, Keepalive, LoadMode, LoadPolicy};

        let mut lifecycle: idoris_contracts::ComponentCard =
            serde_yaml::from_str(include_str!("../../../config/components/omlx.yaml")).unwrap();
        lifecycle.provider.id = "lifecycle".into();
        let mut direct = lifecycle.clone();
        direct.provider.id = "direct".into();
        direct.load_policy = Some(LoadPolicy {
            mode: LoadMode::Resident,
            keepalive: Keepalive::Pinned { pinned: true },
            admission: Admission::Coexist,
        });
        assert!(lifecycle.validate().is_ok());
        assert!(direct.validate().is_ok());
        assert!(crate::dispatch::is_resident_http_service(&direct));

        let adapter = Arc::new(MockAdapter::new(vec![ModelInfo {
            id: "ignored-model".into(),
            memory_gb: 42.0,
        }]));
        let handle = Supervisor::spawn(adapter, SupervisorConfig::default()).unwrap();
        let runtimes = crate::runtime::RuntimeRegistry::from(
            crate::dispatch::BoundSupervisor::new(&lifecycle, handle),
        );
        let state = AppState {
            cards: vec![lifecycle, direct],
            runtimes,
            ..AppState::default()
        };

        let snapshot = backends(&state);
        assert_eq!(snapshot.len(), 2);
        assert_eq!(snapshot[0].provider_id, "lifecycle");
        assert_eq!(
            snapshot[0].locality,
            idoris_contracts::provider::Locality::Loopback
        );
        assert_eq!(
            snapshot[0].form,
            idoris_contracts::component_card::Form::HttpService
        );
        assert!(snapshot[0].lifecycle_runtime_bound);
        assert_eq!(snapshot[1].provider_id, "direct");
        assert_eq!(
            snapshot[1].locality,
            idoris_contracts::provider::Locality::Loopback
        );
        assert_eq!(
            snapshot[1].form,
            idoris_contracts::component_card::Form::HttpService
        );
        assert!(!snapshot[1].lifecycle_runtime_bound);

        let value = serde_json::to_value(&snapshot[0]).unwrap();
        assert_eq!(
            value.as_object().unwrap().keys().collect::<Vec<_>>(),
            ["form", "lifecycle_runtime_bound", "locality", "provider_id"]
        );
        assert!(value.get("health").is_none());
        assert!(value.get("models").is_none());
        assert!(value.get("memory_pressure").is_none());
        assert!(value.get("endpoint").is_none());
    }

    #[tokio::test]
    async fn runtimes_snapshot_reports_observed_status_for_each_lifecycle_runtime() {
        use std::sync::Arc;

        use idoris_backend::{MockAdapter, ModelInfo, Pressure, Supervisor, SupervisorConfig};
        use idoris_contracts::load_policy::{Admission, Keepalive, LoadMode, LoadPolicy};

        fn card(id: &str) -> idoris_contracts::ComponentCard {
            let mut card: idoris_contracts::ComponentCard =
                serde_yaml::from_str(include_str!("../../../config/components/omlx.yaml")).unwrap();
            card.provider.id = id.into();
            card
        }

        fn policy() -> LoadPolicy {
            LoadPolicy {
                mode: LoadMode::OnDemand,
                keepalive: Keepalive::IdleTtl { idle_ttl_s: 300 },
                admission: Admission::Coexist,
            }
        }

        let card_a = card("runtime-a");
        let adapter_a = Arc::new(MockAdapter::new(vec![ModelInfo {
            id: "alpha".into(),
            memory_gb: 8.0,
        }]));
        let handle_a = Supervisor::spawn(
            adapter_a,
            SupervisorConfig {
                budget_gb: 8.0,
                ..SupervisorConfig::default()
            },
        )
        .unwrap();
        handle_a.load("alpha", 8.0, policy()).await.unwrap();

        let card_b = card("runtime-b");
        let adapter_b = Arc::new(MockAdapter::new(vec![ModelInfo {
            id: "beta".into(),
            memory_gb: 13.0,
        }]));
        let handle_b = Supervisor::spawn(
            adapter_b,
            SupervisorConfig {
                budget_gb: 16.0,
                ..SupervisorConfig::default()
            },
        )
        .unwrap();
        handle_b.load("beta", 13.0, policy()).await.unwrap();

        let mut direct = card("direct-resident");
        direct.load_policy = Some(LoadPolicy {
            mode: LoadMode::Resident,
            keepalive: Keepalive::Pinned { pinned: true },
            admission: Admission::Coexist,
        });
        assert!(crate::dispatch::is_resident_http_service(&direct));

        let registry = crate::runtime::RuntimeRegistry::from_supervisors([
            crate::dispatch::BoundSupervisor::new(&card_a, handle_a),
            crate::dispatch::BoundSupervisor::new(&card_b, handle_b),
        ]);
        let snapshot = runtimes(&AppState {
            cards: vec![card_a, card_b, direct],
            runtimes: registry,
            ..AppState::default()
        })
        .await;

        assert_eq!(snapshot.runtimes.len(), 2);
        assert_eq!(
            snapshot.runtimes[0],
            AdminRuntime {
                provider_id: "runtime-a".into(),
                state: AdminRuntimeState::Observed,
                pressure: Some(Pressure::Hard),
                used_gb: Some(8.0),
                model_memory_max_gb: Some(8.0),
                loaded: Some(vec!["alpha".into()]),
            }
        );
        assert_eq!(
            snapshot.runtimes[1],
            AdminRuntime {
                provider_id: "runtime-b".into(),
                state: AdminRuntimeState::Observed,
                pressure: Some(Pressure::Soft),
                used_gb: Some(13.0),
                model_memory_max_gb: Some(16.0),
                loaded: Some(vec!["beta".into()]),
            }
        );
        assert!(
            snapshot
                .runtimes
                .iter()
                .all(|runtime| runtime.provider_id != "direct-resident")
        );
    }

    #[test]
    fn runtime_status_failure_is_explicit_without_raw_error_or_fake_values() {
        let raw_secret = "backend token=secret should never escape";
        let runtime = map_runtime_status(
            "failed-runtime".into(),
            Err(idoris_backend::BackendError::Upstream {
                message: raw_secret.into(),
            }),
        );

        assert_eq!(runtime.state, AdminRuntimeState::Error);
        assert_eq!(runtime.pressure, None);
        assert_eq!(runtime.used_gb, None);
        assert_eq!(runtime.model_memory_max_gb, None);
        assert_eq!(runtime.loaded, None);
        let json = serde_json::to_value(&runtime).unwrap();
        assert_eq!(
            json,
            serde_json::json!({"provider_id":"failed-runtime","state":"error"})
        );
        assert!(
            !serde_json::to_string(&runtime)
                .unwrap()
                .contains(raw_secret)
        );
    }

    #[tokio::test]
    async fn models_snapshot_keeps_observed_configured_and_error_sources_distinct() {
        use crate::subscription::config::{SANDBOX_PROFILE_ID, SubscriptionConfig};
        use crate::subscription::runtime::{
            SubscriptionRuntimeHandle, SubscriptionRuntimeRegistry, authorize_subscription,
        };

        let observed_server = MockServer::start().await;
        Mock::given(method("GET"))
            .and(path("/v1/models"))
            .respond_with(ResponseTemplate::new(200).set_body_json(serde_json::json!({
                "data": [{"id": "observed-a"}, {"id": "observed-b"}]
            })))
            .expect(1)
            .mount(&observed_server)
            .await;
        let failed_server = MockServer::start().await;
        Mock::given(method("GET"))
            .and(path("/v1/models"))
            .respond_with(ResponseTemplate::new(500))
            .expect(1)
            .mount(&failed_server)
            .await;
        let auth_server = MockServer::start().await;
        Mock::given(method("GET"))
            .and(path("/v1/models"))
            .respond_with(ResponseTemplate::new(401))
            .expect(1)
            .mount(&auth_server)
            .await;

        let mut observed: idoris_contracts::ComponentCard =
            serde_yaml::from_str(include_str!("../../../config/components/omlx.yaml")).unwrap();
        observed.provider.id = "observed".into();
        observed.endpoint = observed_server.uri();
        observed.version_pin = "test@1".into();
        let mut failed = observed.clone();
        failed.provider.id = "failed".into();
        failed.endpoint = failed_server.uri();
        let mut auth_failed = observed.clone();
        auth_failed.provider.id = "auth-failed".into();
        auth_failed.endpoint = auth_server.uri();

        let subscription: idoris_contracts::ComponentCard =
            serde_yaml::from_str(include_str!("../../../config/components/subscription.yaml"))
                .unwrap();
        let config = SubscriptionConfig::snapshot(
            Some("personal"),
            Some("1"),
            None,
            Some(SANDBOX_PROFILE_ID),
            Some("codex"),
        );
        let authorized = authorize_subscription(&config, &subscription)
            .unwrap()
            .unwrap();
        let handle = SubscriptionRuntimeHandle::build(authorized, &subscription).unwrap();
        let mut subscriptions = SubscriptionRuntimeRegistry::default();
        subscriptions.insert(handle).unwrap();

        let state = AppState {
            cards: vec![observed, failed, auth_failed, subscription],
            subscriptions,
            ..AppState::default()
        };
        let snapshot = models(&state).await;
        assert_eq!(snapshot.sources.len(), 4);
        assert_eq!(
            snapshot.sources[0],
            AdminModelSource {
                provider_id: "observed".into(),
                source: AdminModelSourceKind::HttpModelsEndpoint,
                state: AdminModelSourceState::Observed,
                models: vec!["observed-a".into(), "observed-b".into()],
                error: None,
            }
        );
        assert_eq!(
            snapshot.sources[1],
            AdminModelSource {
                provider_id: "failed".into(),
                source: AdminModelSourceKind::HttpModelsEndpoint,
                state: AdminModelSourceState::Error,
                models: vec![],
                error: Some(AdminModelSourceError::Unavailable),
            }
        );
        assert_eq!(
            snapshot.sources[2],
            AdminModelSource {
                provider_id: "auth-failed".into(),
                source: AdminModelSourceKind::HttpModelsEndpoint,
                state: AdminModelSourceState::Error,
                models: vec![],
                error: Some(AdminModelSourceError::AuthenticationFailed),
            }
        );
        assert_eq!(
            snapshot.sources[3],
            AdminModelSource {
                provider_id: "subscription".into(),
                source: AdminModelSourceKind::SubscriptionRegistration,
                state: AdminModelSourceState::Configured,
                models: vec!["codex-subscription".into()],
                error: None,
            }
        );
        let value = serde_json::to_value(snapshot).unwrap();
        assert!(
            value.get("data").is_none(),
            "must not publish a flat complete-looking list"
        );
        observed_server.verify().await;
        failed_server.verify().await;
        auth_server.verify().await;
    }

    #[tokio::test]
    async fn models_snapshot_rejects_partial_http_observations_but_accepts_empty() {
        let mixed_server = MockServer::start().await;
        Mock::given(method("GET"))
            .and(path("/v1/models"))
            .respond_with(ResponseTemplate::new(200).set_body_json(serde_json::json!({
                "data": [{"id": "valid"}, {"id": 7}]
            })))
            .expect(1)
            .mount(&mixed_server)
            .await;
        let invalid_server = MockServer::start().await;
        Mock::given(method("GET"))
            .and(path("/v1/models"))
            .respond_with(ResponseTemplate::new(200).set_body_json(serde_json::json!({
                "data": [{"id": 7}, {"not_id": "x"}]
            })))
            .expect(1)
            .mount(&invalid_server)
            .await;
        let empty_server = MockServer::start().await;
        Mock::given(method("GET"))
            .and(path("/v1/models"))
            .respond_with(ResponseTemplate::new(200).set_body_json(serde_json::json!({
                "data": []
            })))
            .expect(1)
            .mount(&empty_server)
            .await;

        let mut mixed: idoris_contracts::ComponentCard =
            serde_yaml::from_str(include_str!("../../../config/components/omlx.yaml")).unwrap();
        mixed.provider.id = "mixed".into();
        mixed.endpoint = mixed_server.uri();
        mixed.version_pin = "test@1".into();
        let mut invalid = mixed.clone();
        invalid.provider.id = "invalid".into();
        invalid.endpoint = invalid_server.uri();
        let mut empty = mixed.clone();
        empty.provider.id = "empty".into();
        empty.endpoint = empty_server.uri();

        let snapshot = models(&AppState {
            cards: vec![mixed, invalid, empty],
            ..AppState::default()
        })
        .await;
        assert_eq!(snapshot.sources.len(), 3);
        for source in &snapshot.sources[..2] {
            assert_eq!(source.state, AdminModelSourceState::Error);
            assert_eq!(source.error, Some(AdminModelSourceError::Unavailable));
            assert!(source.models.is_empty());
        }
        assert_eq!(snapshot.sources[2].state, AdminModelSourceState::Observed);
        assert_eq!(snapshot.sources[2].error, None);
        assert!(snapshot.sources[2].models.is_empty());

        mixed_server.verify().await;
        invalid_server.verify().await;
        empty_server.verify().await;
    }

    #[test]
    fn roles_snapshot_locks_contract_order_aliases_and_catalog_semantics() {
        let expected = [
            ("fast", "idoris/fast", true),
            ("daily", "idoris/daily", true),
            ("deep", "idoris/deep", true),
            ("vision", "idoris/vision", true),
            ("embed", "idoris/embed", true),
            ("rerank", "idoris/rerank", true),
            ("decide", "idoris/decide", true),
            ("auto", "idoris/auto", false),
        ];
        let snapshot = roles();

        assert_eq!(snapshot.len(), expected.len());
        for (entry, (role, alias, catalog_role)) in snapshot.iter().zip(expected) {
            assert_eq!(entry.role, role);
            assert_eq!(entry.aliases, [alias]);
            assert_eq!(entry.catalog_role, catalog_role);
        }

        let value = serde_json::to_value(snapshot).unwrap();
        assert_eq!(
            value,
            serde_json::json!([
                {"role":"fast","aliases":["idoris/fast"],"catalog_role":true},
                {"role":"daily","aliases":["idoris/daily"],"catalog_role":true},
                {"role":"deep","aliases":["idoris/deep"],"catalog_role":true},
                {"role":"vision","aliases":["idoris/vision"],"catalog_role":true},
                {"role":"embed","aliases":["idoris/embed"],"catalog_role":true},
                {"role":"rerank","aliases":["idoris/rerank"],"catalog_role":true},
                {"role":"decide","aliases":["idoris/decide"],"catalog_role":true},
                {"role":"auto","aliases":["idoris/auto"],"catalog_role":false},
            ])
        );
    }

    #[test]
    fn default_status_reports_only_real_configured_surfaces() {
        let state = AppState::default();
        let status = status(&state);

        assert_eq!(status.status, "ok");
        assert_eq!(status.service, "idoris");
        assert_eq!(status.contract_version, idoris_contracts::CONTRACT_VERSION);
        assert_eq!(status.instance_id, state.instance_id);
        assert_eq!(status.components, 0);
        assert_eq!(status.runtimes, 0);
        assert_eq!(status.subscriptions, 0);
        assert!(!status.budget_configured);
        assert!(!status.audit_configured);
    }

    #[test]
    fn session_tokens_are_fresh_redacted_and_constant_time_verifiable() {
        let first = AdminSessionToken::mint();
        let second = AdminSessionToken::mint();

        assert_eq!(first.expose_secret().len(), SESSION_TOKEN_LEN);
        assert_ne!(first.expose_secret(), second.expose_secret());
        assert!(first.matches(first.expose_secret()));
        assert!(!first.matches(second.expose_secret()));
        assert!(!first.matches("short"));
        assert_eq!(format!("{first}"), "[REDACTED]");
        assert_eq!(format!("{first:?}"), "AdminSessionToken([REDACTED])");
    }
}
